### ISSUE TITLE
Active thoughts on features

### ISSUE THREAD

**Issue by sacOO7** [RocketChat/Rocket.Chat.Android.SDK#1]
I have added some of the features in readme file, but I think it is equally necessary to discuss and finalize them together. So we can discuss related thoughts in this thread :)

**Comment by sacOO7** [comment]
Please reply someone on this thread .....

**Comment by Naguchennai** [comment]
How can We use this? u need add more details.. create android compile

**Comment by sacOO7** [comment]
Hey it's not complete yet, currently trying to implement Livechat SDK. Core SDK will be implemented in upcoming weeks. Meanwhile you should read about LiveChat feature in rocket.chat.

**Comment by sacOO7** [comment]
@naguchennai added doc, you can now refer it

**Comment by Naguchennai** [comment]
I think u must rename it. Its not "Rocket chat android sdk".. its "Rocket chat live chat sdk"

**Comment by sacOO7** [comment]
Its still under development and core part is yet to be implemented. Current focus is on dev. of livechat functionality. If you want core SDK, you have to wait for it :)
