### ISSUE TITLE
Can not login after registerGuest

### ISSUE THREAD

**Issue by bochitan** [RocketChat/Rocket.Chat.Android.SDK#7]
Hi all, 

First of all, thanks for sharing code,
I have downloaded this app, run successfull but can not chat on mobile, although can chat on web

after call method livechat:registerGuest, i got userId only without authToken. So can not login to get live chat with agent.

Please view below code
---
@Override
    public void onRegister(GuestObject object, final ErrorObject error) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (error!=null){
                    AppUtils.showToast(SignupActivity.this, error.getMessage() , false);
                    dialog.dismiss();
                }else {
                    AppUtils.showToast(SignupActivity.this, "Registration successful", false);
                    dialog.dismiss();
                }
            }
        });
        if (error==null) {
            **api.login(object.getToken(), this);**
        }
    }

------

I already check code on server.  Code of livechat:registerGuest changed already, no return authToken already.

Meteor.methods({
	'livechat:registerGuest'({ token, name, email, department } = {}) {
		const userId = RocketChat.Livechat.registerGuest.call(this, {
			token,
			name,
			email,
			department
		});

		// update visited page history to not expire
		RocketChat.models.LivechatPageVisited.keepHistoryForToken(token);

		return {
			userId
		};
	}
});

--
How can i use this livechat android?

And i found livechat iOS SDK but nothing, can you show me ?

Sorry for my bad english,

Thanks

**Comment by philipbrito** [comment]
Hi @bochitan!

This repository will be archived very soon in favor of our [new repository](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK).

You can take a look on how we are using the new SDK on our new Android app [here](https://github.com/RocketChat/Rocket.Chat.Android).

**Comment by bochitan** [comment]
Do this repository has livechat SDK, i need it?
I take a look but nothing about livechat.

Thanks for your response

**Comment by philipbrito** [comment]
The `livechat` is not implemented there yet. But we are working hard to put a lot of features on the SDK as fast as we can.
